import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Montserrat, Lato } from 'next/font/google';
import ClientProviders from "@/components/ClientProviders";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat',
});

// const lato = Lato({
//     subsets: ['latin'],
//     weight: ['400', '700'],
//     variable: '--font-lato',
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body>
        <ClientProviders>
          <Navbar />
          <div className="min-h-screen page-transition">{children}</div>
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}

